"""KnowledgeRepositoryPort backed by `data/knowledge-base.md`.

The markdown file is the single source of truth for all downstream
agents, per AGENTS.md Decision Log - editable, diffable, and readable by
any agent without parsing overhead. `save()` renders each section as a
markdown table from validated domain models (never raw agent text
directly, see build_knowledge_base.py); `load()` parses those tables back
into the same domain models, tolerant of hand edits (added/removed rows,
extra whitespace). A trailing free-form "Notes" section is preserved
verbatim across rebuilds for anything a human wants to add that doesn't
fit the structured shape.
"""

from __future__ import annotations

import re
import typing
from pathlib import Path

from pydantic import BaseModel

from cvpal.domain.knowledge.models import (
    CertificationEntry,
    EducationEntry,
    ExperienceBullet,
    KnowledgeBase,
    LanguageEntry,
    PersonalDataField,
    ProjectEntry,
    SkillEntry,
    SummaryEntry,
)
from cvpal.domain.knowledge.voice import VoiceProfile

_HEADER = """\
# Bruno Vargas Tettamanti — Knowledge Base

> Single source of truth for all CV content, skills, experience, and voice profile.
> Maintained manually after initial bootstrap, and re-generated by `cvpal kb build`
> when new source CVs are added - hand edits inside each table survive as long as
> the row shape is kept; free-form text belongs in the Notes section at the bottom.
> Language: English (translation to Spanish/other happens at generation time).
"""

_SECTIONS: list[tuple[str, str, type[BaseModel]]] = [
    ("personal_data", "Personal Data", PersonalDataField),
    ("summaries", "Summary", SummaryEntry),
    ("experience", "Experience", ExperienceBullet),
    ("education", "Education", EducationEntry),
    ("certifications", "Certifications", CertificationEntry),
    ("skills", "Skills", SkillEntry),
    ("projects", "Projects", ProjectEntry),
    ("languages", "Languages", LanguageEntry),
]

_VOICE_LIST_FIELDS = {"recurring_phrases", "tone_summary"}
_NOTES_MARKER = "<!-- cvpal:notes -->"


def _cell_str(value: object) -> str:
    if isinstance(value, list):
        text = ", ".join(str(v) for v in value)
    elif value is None:
        text = ""
    else:
        text = str(value)
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _render_table(rows: list[BaseModel], model_type: type[BaseModel]) -> str:
    fields = list(model_type.model_fields.keys())
    if not rows:
        return "_(none)_"
    lines = [
        "| " + " | ".join(fields) + " |",
        "|" + "|".join(["---"] * len(fields)) + "|",
    ]
    for row in rows:
        dumped = row.model_dump()
        lines.append("| " + " | ".join(_cell_str(dumped[f]) for f in fields) + " |")
    return "\n".join(lines)


def _render_section(key: str, heading: str, rows: list[BaseModel], model_type: type[BaseModel]) -> str:
    return "\n".join(
        [
            f"<!-- cvpal:section={key} -->",
            f"## {heading}",
            "",
            _render_table(rows, model_type),
            "<!-- /cvpal:section -->",
        ]
    )


def _render_voice_profile(voice: VoiceProfile | None) -> str:
    lines = ["<!-- cvpal:section=voice_profile -->", "## Voice Profile", ""]
    if voice is None:
        lines.append("_(not yet extracted)_")
    else:
        lines.append("| Trait | Value |")
        lines.append("|---|---|")
        dumped = voice.model_dump()
        for field_name in VoiceProfile.model_fields:
            value = dumped[field_name]
            cell = "; ".join(value) if isinstance(value, list) else str(value)
            lines.append(f"| {field_name} | {_cell_str(cell)} |")
    lines.append("<!-- /cvpal:section -->")
    return "\n".join(lines)


def _split_row(line: str) -> list[str]:
    line = line.strip()
    if line.startswith("|"):
        line = line[1:]
    if line.endswith("|"):
        line = line[:-1]
    cells = re.split(r"(?<!\\)\|", line)
    return [c.strip().replace("\\|", "|") for c in cells]


def _parse_table(block: str) -> list[dict[str, str]]:
    lines = [line for line in block.strip().splitlines() if line.strip().startswith("|")]
    if len(lines) < 2:
        return []
    header = _split_row(lines[0])
    rows: list[dict[str, str]] = []
    for line in lines[2:]:  # skip header + separator row
        cells = _split_row(line)
        if len(cells) != len(header):
            continue
        rows.append(dict(zip(header, cells)))
    return rows


def _rows_to_models(raw_rows: list[dict[str, str]], model_type: type[BaseModel]) -> list[BaseModel]:
    results = []
    for raw in raw_rows:
        converted: dict[str, object] = {}
        for field_name, field_info in model_type.model_fields.items():
            value = raw.get(field_name, "")
            if typing.get_origin(field_info.annotation) is list:
                converted[field_name] = [v.strip() for v in value.split(",") if v.strip()]
            else:
                converted[field_name] = value
        results.append(model_type.model_validate(converted))
    return results


def _extract_section_block(text: str, key: str) -> str | None:
    pattern = rf"<!-- cvpal:section={re.escape(key)} -->(.*?)<!-- /cvpal:section -->"
    match = re.search(pattern, text, re.DOTALL)
    return match.group(1) if match else None


def _parse_voice_profile(block: str) -> VoiceProfile | None:
    raw_rows = _parse_table(block)
    if not raw_rows:
        return None
    data: dict[str, object] = {}
    for row in raw_rows:
        field_name = row.get("Trait", "").strip()
        value = row.get("Value", "").strip()
        if field_name in _VOICE_LIST_FIELDS:
            data[field_name] = [v.strip() for v in value.split(";") if v.strip()]
        else:
            data[field_name] = value
    return VoiceProfile.model_validate(data) if data else None


class MarkdownKnowledgeRepository:
    def __init__(self, path: Path) -> None:
        self._path = path

    def exists(self) -> bool:
        return self._path.exists()

    def save(self, knowledge_base: KnowledgeBase) -> None:
        parts = [_HEADER]
        for key, heading, model_type in _SECTIONS:
            rows = getattr(knowledge_base, key)
            parts.append(_render_section(key, heading, rows, model_type))
        parts.append(_render_voice_profile(knowledge_base.voice_profile))
        parts.append(_NOTES_MARKER + "\n## Notes\n\n" + (knowledge_base.notes or "_(none)_"))

        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._path.write_text("\n\n".join(parts) + "\n")

    def load(self) -> KnowledgeBase:
        text = self._path.read_text()
        kwargs: dict[str, object] = {}
        for key, _heading, model_type in _SECTIONS:
            block = _extract_section_block(text, key)
            raw_rows = _parse_table(block) if block else []
            kwargs[key] = _rows_to_models(raw_rows, model_type)

        voice_block = _extract_section_block(text, "voice_profile")
        kwargs["voice_profile"] = _parse_voice_profile(voice_block) if voice_block else None

        notes_match = re.search(re.escape(_NOTES_MARKER) + r"\n## Notes\n\n(.*)$", text, re.DOTALL)
        notes = notes_match.group(1).strip() if notes_match else ""
        kwargs["notes"] = "" if notes == "_(none)_" else notes

        return KnowledgeBase(**kwargs)
